#@ load("@ytt:data", "data")

---
apiVersion: carto.run/v1alpha1
kind: ClusterDelivery
metadata:
  name: delivery-basic-w-db
spec:
  selector:
    app.tanzu.vmware.com/deliverable-type: web-db

  resources:
  - name: source-provider
    templateRef:
      kind: ClusterSourceTemplate
      name: delivery-source-template
    params:
    - name: serviceAccount
      value: #@ data.values.service_account
  - name: deployer
    templateRef:
      kind: ClusterDeploymentTemplate
      name: app-deploy
    params:
      - name: serviceAccount
        value: #@ data.values.service_account
    deployment:
      resource: source-provider
