---
apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: simple-database
spec:
  params:
    - name: serviceAccount
      default: default
  ytt: |
    #@ load("@ytt:data", "data")
    #@ load("@ytt:yaml", "yaml")
    ---
    apiVersion: kappctrl.k14s.io/v1alpha1
    kind: App
    metadata:
      name: #@ data.values.workload.metadata.name + "-db"
    spec:
      syncPeriod: 10m
      serviceAccountName: #@ data.values.params.serviceAccount 

      fetch:
      - helmChart:
          name: #@ data.values.params.helm_name
          version: #@ data.values.params.helm_version
          repository:
            url: #@ data.values.params.helm_url
      template:
      #@ if (data.values.params.helm_values):
      - helmTemplate:
          valuesFrom:
          - configMapRef:
              name: #@ data.values.workload.metadata.name + "-helm-values"
      #@ else:
      - helmTemplate: {}
      #@ end
      - ytt: {}
      - kbld: {}
      deploy:
      - kapp: {}
    
